/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_BASE_HPP_
#define V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_BASE_HPP_

#include <v0/filetransfer/example/FileTransfer.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace filetransfer {
namespace example {

class FileTransferProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        uint32_t, CommonAPI::ByteBuffer, bool
    > FileChunkEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const bool&)> RequestFileAsyncCallback;

    virtual void requestFile(std::string _fileName, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> requestFileAsync(const std::string &_fileName, RequestFileAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual FileChunkEvent& getFileChunkEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace example
} // namespace filetransfer
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_FILETRANSFER_EXAMPLE_File_Transfer_PROXY_BASE_HPP_
